// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddSymbol(arg1:string,arg2:string):Promise<models.Stock>;

export function AddTransaction(arg1:models.Transaction):Promise<number>;

export function CreateAlert(arg1:number,arg2:string,arg3:number):Promise<number>;

export function CreatePortfolio(arg1:string,arg2:string,arg3:number):Promise<models.Portfolio>;

export function DeleteAlert(arg1:number):Promise<void>;

export function DeletePortfolio(arg1:number):Promise<void>;

export function GetAlerts():Promise<Array<models.Alert>>;

export function GetChartData(arg1:number,arg2:string):Promise<models.ChartData>;

export function GetExchanges():Promise<Array<models.Exchange>>;

export function GetOHLCV(arg1:number,arg2:string):Promise<string>;

export function GetPollingInterval():Promise<number>;

export function GetPortfolioSummary(arg1:number):Promise<models.PortfolioSummary>;

export function GetPortfolios():Promise<Array<models.Portfolio>>;

export function GetTheme():Promise<string>;

export function GetTransactions(arg1:number):Promise<Array<models.Transaction>>;

export function GetWatchlist(arg1:number):Promise<Array<models.StockWithQuote>>;

export function GetWindowState():Promise<number|number>;

export function Ping():Promise<string>;

export function RefreshAll(arg1:number):Promise<Array<models.StockWithQuote>>;

export function RemoveSymbol(arg1:number):Promise<void>;

export function SaveWindowState(arg1:number,arg2:number):Promise<void>;

export function SearchSymbol(arg1:string):Promise<Array<models.SymbolSuggestion>>;

export function SetPollingInterval(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartPolling(arg1:number,arg2:number):Promise<void>;

export function StopPolling():Promise<void>;

export function ToggleAlert(arg1:number,arg2:boolean):Promise<void>;
