// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSymbol(arg1, arg2) {
  return window['go']['main']['App']['AddSymbol'](arg1, arg2);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function CreateAlert(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAlert'](arg1, arg2, arg3);
}

export function CreatePortfolio(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePortfolio'](arg1, arg2, arg3);
}

export function DeleteAlert(arg1) {
  return window['go']['main']['App']['DeleteAlert'](arg1);
}

export function DeletePortfolio(arg1) {
  return window['go']['main']['App']['DeletePortfolio'](arg1);
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetChartData(arg1, arg2) {
  return window['go']['main']['App']['GetChartData'](arg1, arg2);
}

export function GetExchanges() {
  return window['go']['main']['App']['GetExchanges']();
}

export function GetOHLCV(arg1, arg2) {
  return window['go']['main']['App']['GetOHLCV'](arg1, arg2);
}

export function GetPollingInterval() {
  return window['go']['main']['App']['GetPollingInterval']();
}

export function GetPortfolioSummary(arg1) {
  return window['go']['main']['App']['GetPortfolioSummary'](arg1);
}

export function GetPortfolios() {
  return window['go']['main']['App']['GetPortfolios']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function GetWatchlist(arg1) {
  return window['go']['main']['App']['GetWatchlist'](arg1);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RefreshAll(arg1) {
  return window['go']['main']['App']['RefreshAll'](arg1);
}

export function RemoveSymbol(arg1) {
  return window['go']['main']['App']['RemoveSymbol'](arg1);
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}

export function SearchSymbol(arg1) {
  return window['go']['main']['App']['SearchSymbol'](arg1);
}

export function SetPollingInterval(arg1) {
  return window['go']['main']['App']['SetPollingInterval'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartPolling(arg1, arg2) {
  return window['go']['main']['App']['StartPolling'](arg1, arg2);
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}

export function ToggleAlert(arg1, arg2) {
  return window['go']['main']['App']['ToggleAlert'](arg1, arg2);
}
